#!/usr/bin/env python
from motu_datastore_client import DatastoreClient
import asyncio
import logging
import argparse

logger: logging.Logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.StreamHandler()],
)

async def main():
    parser = argparse.ArgumentParser(
        prog='motu_datastore_client',
        description="Run the AVB Datstore Client"
    )
    parser.add_argument('avbserver', type=str, help="The url of the MOTU AVB server, e.g. http://1248.local")
    args = parser.parse_args()
    def write_message(message):
        logger.info(message)

    client = DatastoreClient(args.avbserver)
    task = asyncio.create_task(client.run(write_message))
    await asyncio.wait([task])

if __name__ == '__main__':
    asyncio.run(main())
    